name = "whaleperp-v2"
main = "src/workers/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "POSITION_MANAGER"
class_name = "PositionManager"
script_name = "whaleperp-v2"

[[migrations]]
tag = "v1"
new_classes = ["PositionManager"]
