[[ai.workers]]
binding = "AI"
model = "@cf/mistralai/mistral-small-3.1-24b-instruct"

[[ai.workers]]
binding = "AI"
model = "@cf/qwen/qwen2.5-coder-32b-instruct"

[[ai.workers]]
binding = "AI"
model = "@hf/mistral/mistral-7b-instruct-v0.2"
